from py4godot.classes.Object import Object

class ClassDB(Object):
    @staticmethod
    def instance() -> ClassDB: ...
    def class_exists(self, class_name: str) -> bool: ...
    def class_call_static(self, class_name: str, method: str, *arguments: object) -> object: ...
