from py4godot.classes.Object import Object

class DisplayServer(Object):
    @staticmethod
    def instance() -> DisplayServer: ...
    def window_set_flag(self, flag: int, enabled: bool, window_id: int = 0) -> None: ...
    def window_set_mode(self, mode: int, window_id: int = 0) -> None: ...
    def window_set_position(self, position: object, window_id: int = 0) -> None: ...
