from py4godot.classes.Object import Object
from py4godot.classes.SceneTree import SceneTree

class Node(Object):
    def get_tree(self) -> SceneTree: ...
    def get_node(self, path: str) -> Node: ...
    def get_node_or_null(self, path: str) -> Node | None: ...
    def add_child(self, node: Node) -> None: ...
    def remove_child(self, node: Node) -> None: ...
    def queue_free(self) -> None: ...
