from typing import Protocol

from py4godot.classes.Object import Object
from py4godot.classes.SceneTree import SceneTree

class NodePathView(Protocol):
    """Minimal typed view of the engine NodePath surface used by host scripts."""

    def is_absolute(self) -> bool: ...
    def get_concatenated_names(self) -> object: ...

class Node(Object):
    def get_tree(self) -> SceneTree: ...
    def get_node(self, path: str) -> Node: ...
    def get_node_or_null(self, path: str) -> Node | None: ...
    def get_path(self) -> NodePathView: ...
    def add_child(self, node: Node) -> None: ...
    def remove_child(self, node: Node) -> None: ...
    def queue_free(self) -> None: ...
    def set_meta(self, name: str, value: object) -> None: ...
