class Object:
    def has_meta(self, name: str) -> bool: ...
    def get_meta(self, name: str, default: object = None) -> object: ...
    def has_method(self, method: str) -> bool: ...
    def call(self, method: str, *arguments: object) -> object: ...
    def call_deferred(self, method: str, *arguments: object) -> object: ...
