from py4godot.classes.Object import Object

class OS(Object):
    @staticmethod
    def instance() -> OS: ...
    def get_environment(self, variable: str) -> str: ...
    def get_name(self) -> str: ...
    def get_processor_name(self) -> str: ...
