from py4godot.classes.Object import Object

class RenderingServer(Object):
    @staticmethod
    def instance() -> RenderingServer: ...
    def get_video_adapter_name(self) -> str: ...
    def get_video_adapter_api_version(self) -> str: ...
